services:
  _defaults:
    public: true

  prestashop.module.search_log.grid.data.factory.search_log:
    class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
    arguments:
      - '@prestashop.module.search_log.grid.query_builder.search_log'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'searchlog'
